"""Collects all functions and logic to calculate 'Specifically Calculated 
Atomic form factors' (SCAFF) for structures. This includes but is not limited
to atomic form factors generated by Hirshfeld partitioning"""

from .LCAODensityCalculators import ORCADensityCalculator, GaussianDensityCalculator