"""Collects all functions and logic to calculate 'Specifically Calculated 
Atomic form factors' (SCAFF) for structures. This includes but is not limited
to atomic form factors generated by Hirshfeld partitioning"""

from .LCAODensityCalculators.orca import ORCADensityCalculator
from .LCAODensityCalculators.gaussian import GaussianDensityCalculator
from .LCAODensityCalculators.nwchem import NWChemLCAODensityCalculator
from .LCAODensityPartitioners.nosphera2 import NoSpherA2Partitioner
from .LCAODensityPartitioners.horton import HortonPartitioner
from .RegGridDensityCalculators.gpaw import GPAWDensityCalculator
from .RegGridDensityPartitioners.python import PythonRegGridPartitioner